[package]
name = "bamegoy-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
bamegoy-core = { path = "../emulator" }
catppuccin = "2.5.1"
eframe = "0.31.1"
egui = "0.31.1"
egui_extras = "0.31.1"
env_logger = "0.11.8"